pool:
   vmImage: 'ubuntu-latest'   
variables:
   buildConfiguration: 'Release' 
steps:
  - task: UseDotNet@2
    inputs:
        version: '8.x' # replace this value with the version that you need for your project
  - script: |
        dotnet run  --project ./build/_build.csproj -GitHubAccessToken $(GithubAccessToken)
