pool:
   vmImage: 'ubuntu-latest'   
variables:
   buildConfiguration: 'Release' 
steps:
  - task: UseDotNet@2
    inputs:
        version: '9.x' # updated to .NET 9 for this repository
  - script: |
        dotnet run  --project ./build/_build.csproj -GitHubAccessToken $(GithubAccessToken)
