name: ASP.NET Core CI
on:
  push:
    branches: [ nuke ]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '8.0.x'
    - name: buld with Nuke
      run: dotnet run  --project ./build/_build.csproj -GitHubAccessToken ${{ secrets.GithubAccessToken }}
